Models/CarrinhoCompra.cs
using Lanches_Mac.Contexto;
using Microsoft.EntityFrameworkCore;

namespace Lanches_Mac.Models
{
    public class CarrinhoCompra
    {

        private readonly AppDbContext _context;

        public CarrinhoCompra(AppDbContext context)
        {
            _context = context;
        }

        public string CarrinhoCompraId { get; set; }

        public List<CarrinhoCompraItem> CarrinhoCompraItems { get; set; }

        public static CarrinhoCompra GetCarrinho(IServiceProvider services)
        {
            //Define uma sessão
            ISession session =
                services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
            //obtem um serviço do tipo do nosso contexto
            var context = services.GetService<AppDbContext>();

            //obtem ou gera o ID do carrinho
            string carrinhoId = session.GetString("CarrinhoId") ?? Guid.NewGuid().ToString();

            //atribui o id do carrinho na Sessão
            session.SetString("CarrinhoId", carrinhoId);

            //retona o carrinho com o contexto e o Id atribuido puo obtido
            return new CarrinhoCompra(context)
            {
                CarrinhoCompraId = carrinhoId
            };
        }
        public void AdicionarAoCarrinho(Lanche lanche)
        {
            var carrinhocompraItem = _context.CarrinhoCompraItens.SingleOrDefault(
                  s => s.Lanche.LancheId == lanche.LancheId
                  && s.CarrinhoCompraId == CarrinhoCompraId);
            if (carrinhocompraItem == null)
            {
                carrinhocompraItem = new CarrinhoCompraItem
                {
                    CarrinhoCompraId = CarrinhoCompraId,
                    Lanche = lanche,
                    Quantidade = 1
                };
                _context.CarrinhoCompraItens.Add(carrinhocompraItem);

            }
            else
            {
                carrinhocompraItem.Quantidade++;
            }
            _context.SaveChanges();
        }
        public int RemoverDoCarrinho(Lanche lanche)
        {
            var carrinhocompraItem = _context.CarrinhoCompraItens.SingleOrDefault(
                  s => s.Lanche.LancheId == lanche.LancheId
                  && s.CarrinhoCompraId == CarrinhoCompraId);

            var quantidadeLocal = 0;

            if (carrinhocompraItem != null)
            {
                if (carrinhocompraItem.Quantidade > 1)
                {
                    carrinhocompraItem.Quantidade--;
                    quantidadeLocal = carrinhocompraItem.Quantidade;
                }
                else
                {
                    _context.CarrinhoCompraItens.Remove(carrinhocompraItem);

                }
            }
            _context.SaveChanges();
            return quantidadeLocal;
        }
        public List<CarrinhoCompraItem> GetCarrinhoCompraItems()
        {
            return CarrinhoCompraItems ??
                (CarrinhoCompraItems =
                _context.CarrinhoCompraItens
                .Where(c => c.CarrinhoCompraId == CarrinhoCompraId)
                .Include(s => s.Lanche)
                .ToList());
        }
    
        public void LimparCarrinho()
        {
            var carrinhoItens = _context.CarrinhoCompraItens
                .Where(carrinho => 
                carrinho.CarrinhoCompraId == CarrinhoCompraId); ;
            _context.CarrinhoCompraItens.RemoveRange(carrinhoItens);
            _context.SaveChanges();

        }
        public decimal GetCarrinhoCompraTotal()
        {
            var total = _context.CarrinhoCompraItens
              .Where(c => c.CarrinhoCompraId==CarrinhoCompraId)
              .Select(c => c.Lanche.Preco * c.Quantidade).Sum();
            return total;
        }
    }
}

ViewModels/CarrinhoCompraViewModel.cs
using Lanches_Mac.Models;

namespace Lanches_Mac.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra CarrinhoCompra { get; set; }
        public decimal CarrinhoCompraTotal { get; set; }

    }
}

Controllers/CarrinhoCompraController.cs
using Lanches_Mac.Models;
using Lanches_Mac.Repositories;
using Lanches_Mac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Lanches_Mac.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItems();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }
        
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecinado = _lancheRepository.Lanche.FirstOrDefault(p => p.LancheId == lancheId);
            if (lancheSelecinado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecinado);                
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoverItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanche.FirstOrDefault(p => p.LancheId == lancheId);
            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/CarrinhoCompra/Index.cshtml
@model CarrinhoCompraViewModel


<div class="container">
    <div class="row">
        <img src="~/images/full-cart-icon.png" />
        <div>
            <h4>Seu carrinho de compras: </h4>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Quantidade</th>
                    <th>Lanche</th>
                    <th class="text-right">Preço</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.CarrinhoCompra.CarrinhoCompraItems)
                {
                    <tr>

                        <td class="text-center">@item.Quantidade</td>
                        <td class="text-left">@item.Lanche.Nome</td>
                        <td class="text-right">@item.Lanche.Preco.ToString("c")</td>

                        <td class="text-right">
                            @((item.Quantidade * item.Lanche.Preco).ToString("c"));
                        </td>

                        <td class="text-right">
                            <a asp-controller="CarrinhoCompra" asp-action="RemoverItemNoCarrinhoCompra"
                               asp-route-LancheId="@item.Lanche.LancheId">
                                <img src="~/images/delete.png" />
                            </a>
                        </td>

                    </tr>
                }
            </tbody>

            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:  </td>
                    <td class="text-right">
                        @Model.CarrinhoCompraTotal.ToString("c")
                    </td>                
                </tr>
            </tfoot>

        </table>
        <br />

        <div class="text-right">
            <div class="btn-group">
                <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>&ensp;&ensp;&ensp;
                <a class="btn btn-primary" asp-controller="lanche" asp-action="List">Continuar Pedido</a>
            </div>
        </div>

    </div>
</div>